---
- hosts: all

  vars_files:
    - secrets/rhn.yml
    - vars/fqdn.yml

  sudo: yes

  tasks:
    - name: Check RHN subscription
      command: subscription-manager status
      register: rhn_status
      ignore_errors: True
      failed_when: "'Unknown' in rhn_status.stdout"

    - name: Register with RHN subscription
      command: subscription-manager register --username {{ rhn_username }} --password '{{ rhn_password }}' --auto-attach --force
      when: rhn_status | failed

    - name: Yum cleanup
      command: yum clean all
      when: rhn_status | failed

    - name: Remove all subscription-manager repos
      command: subscription-manager repos --disable="*"
      when: rhn_status | failed

    - name: Add Openshift Enterprise beta repos
      command: subscription-manager repos --enable={{ item }}
      when: rhn_status | failed
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-optional-rpms
        - rhel-server-7-ose-beta-rpms

    - name: Stop conflicting services
      service: name={{ item }} state=stopped enabled=no
      with_items:
        - firewalld
        - NetworkManager

    - name: Install deltarpm
      yum: name=deltarpm state=present

    - name: Install dependencies
      yum: name={{ item }} state=present
      with_items:
        - wget
        - vim-enhanced
        - net-tools
        - bind-utils
        - tmux
        - git
        - docker
        - openvswitch
        - iptables-services
        - bridge-utils

    - name: Install openshift
      command: yum -y install '*openshift*'
      register: install_openshift
      changed_when: "'Nothing to do' not in install_openshift.stdout"

    - name: Configure docker
      lineinfile: dest=/etc/sysconfig/docker regexp=^OPTIONS line="OPTIONS='--insecure-registry 0.0.0.0/0'"

    - name: Configure iptables
      copy: src=iptables dest=/etc/sysconfig/iptables

    - name: Configure /etc/hosts
      lineinfile: dest=/etc/hosts regexp=^192\.168\.100\.100 line='192.168.100.100 {{ fqdn.master }}'

    - name: Configure /etc/hosts
      lineinfile: dest=/etc/hosts regexp=^192\.168\.100\.200 line='192.168.100.200 {{ fqdn.node1 }}'

    - name: Configure /etc/hosts
      lineinfile: dest=/etc/hosts regexp=^192\.168\.100\.201 line='192.168.100.201 {{ fqdn.node2 }}'

    - name: Enable services
      service: name={{ item }} state=started enabled=yes
      with_items:
        - docker
        - iptables
        - openvswitch

    - name: Grab docker images
      command: docker pull {{ item }}
      register: docker_images
      changed_when: "'Downloaded newer image' in docker_images.stdout"
      with_items:
        - registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4
        - registry.access.redhat.com/openshift3_beta/ose-deployer:v0.4
        - registry.access.redhat.com/openshift3_beta/ose-sti-builder:v0.4
        - registry.access.redhat.com/openshift3_beta/ose-docker-builder:v0.4
        - registry.access.redhat.com/openshift3_beta/ose-pod:v0.4
        - registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.4
        - openshift/ruby-20-centos7
        - mysql
        - openshift/hello-openshift

    - name: Add openshift-logs alias to vagrant user .bash_profile
      lineinfile: dest=/home/vagrant/.bash_profile insertafter=EOF regexp='^alias openshift-logs' line='alias openshift-logs="sudo journalctl -f --no-pager -l -u openshift-master -u openshift-sdn-master -u openshift-node -u openshift-sdn-node"'

    - name: Add openshift-status alias to vagrant user .bash_profile
      lineinfile: dest=/home/vagrant/.bash_profile insertafter=EOF regexp='^alias openshift-status' line='alias openshift-status="sudo systemctl status openshift-master openshift-sdn-master openshift-node openshift-sdn-node"'

    - name: Create root ssh directory
      file: path=/root/.ssh owner=root group=root mode=0700 state=directory

    - name: Add vagrant ssh private key for root user
      get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant dest=/root/.ssh/id_rsa owner=root group=root mode=0600

    - name: Add vagrant ssh private key for vagrant user
      get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=0600

    - name: Add vagrant ssh public key to root authorized keys
      get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub dest=/root/.ssh/authorized_keys owner=root group=root mode=0600
